### ISSUE TITLE
le menu du haut disparaît quand on remonte en haut de page (dernière version de Safari Mac)

### ISSUE THREAD

**Issue by DeveloppeurPascal** [SnyDrive25/LaPlumeDeVinci#1]
Sur Safari on a un effet (totalement inutile) de rebondi quand on atteint le début ou la fin d'une page web.
Ici, quand on monte avant que leur animation se déclenche le header du site apparaît bien progressivement, en revanche il disparaît quand on est allé au delà.

**Comment by SnyDrive** [comment]
Problème réglé normalement, merci pour la remarque ! 🙂

`JavaScript` Ajout d'un minimum de défilement nécessaire avant la disparition du menu.

**Comment by DeveloppeurPascal** [comment]
en fait c'est pire (ou mon cache n'est pas vidé) ;)
j'te fais une vidéo tout à l'heure

**Comment by DeveloppeurPascal** [comment]
semble corrigé (ou modification dans Safari)

**Comment by SnyDrive** [comment]
> semble corrigé (ou modification dans Safari)

Une correction a été tentée la fois dernière, je pense que c'est en effet votre cache qui s'est vidé et donc maintenant tout fonctionne bien, merci @DeveloppeurPascal pour le retour en tout cas !

- Prochaine MAJ : janvier 2024 le système d'authentification de ma base de données Airtable devra changer :-/
